// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// AccessTokenResponse defines model for AccessTokenResponse.
type AccessTokenResponse struct {
	AccessToken string `json:"access_token"`
}

// ApiResponse defines model for ApiResponse.
type ApiResponse struct {
	Data    *ApiResponse_Data `json:"data"`
	Message *string           `json:"message,omitempty"`
	Status  *int32            `json:"status,omitempty"`
}

// ApiResponseData0 defines model for .
type ApiResponseData0 = map[string]interface{}

// ApiResponseData1 defines model for .
type ApiResponseData1 = []map[string]interface{}

// ApiResponse_Data defines model for ApiResponse.Data.
type ApiResponse_Data struct {
	union json.RawMessage
}

// AuthorizationErrorResponse defines model for AuthorizationErrorResponse.
type AuthorizationErrorResponse struct {
	Code    *int32  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// BadRequestErrorResponse defines model for BadRequestErrorResponse.
type BadRequestErrorResponse struct {
	Code    *int32  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// GenderResponse defines model for GenderResponse.
type GenderResponse struct {
	GenderName *string `json:"genderName,omitempty"`
	Id         *int64  `json:"id,omitempty"`
}

// LoginUserRequest defines model for LoginUserRequest.
type LoginUserRequest struct {
	Email    string `json:"email" validate:"email"`
	Password string `json:"password" validate:"min=8,matches=^[a-zA-Z0-9]*$"`
}

// LoginUserResponse defines model for LoginUserResponse.
type LoginUserResponse struct {
	Data    *AccessTokenResponse `json:"data,omitempty"`
	Message *string              `json:"message,omitempty"`
	Status  *int                 `json:"status,omitempty"`
}

// MaritalStatusesResponse defines model for MaritalStatusesResponse.
type MaritalStatusesResponse struct {
	Id         *int64  `json:"id,omitempty"`
	StatusName *string `json:"statusName,omitempty"`
}

// MultiGendersResponse defines model for MultiGendersResponse.
type MultiGendersResponse struct {
	Data    *[]GenderResponse `json:"data,omitempty"`
	Message *string           `json:"message,omitempty"`
	Status  *int              `json:"status,omitempty"`
}

// MultiMaritalStatusesResponse defines model for MultiMaritalStatusesResponse.
type MultiMaritalStatusesResponse struct {
	Data    *[]MaritalStatusesResponse `json:"data,omitempty"`
	Message *string                    `json:"message,omitempty"`
	Status  *int                       `json:"status,omitempty"`
}

// MultiUserStatusesResponse defines model for MultiUserStatusesResponse.
type MultiUserStatusesResponse struct {
	Data    *[]UserStatusesResponse `json:"data,omitempty"`
	Message *string                 `json:"message,omitempty"`
	Status  *int                    `json:"status,omitempty"`
}

// MultiUsersResponse defines model for MultiUsersResponse.
type MultiUsersResponse struct {
	Data    *[]UserResponse `json:"data,omitempty"`
	Message *string         `json:"message,omitempty"`
	Status  *int            `json:"status,omitempty"`
}

// PutProfileRequest defines model for PutProfileRequest.
type PutProfileRequest struct {
	AddressLine1       string    `json:"addressLine1"`
	AddressLine2       *string   `json:"addressLine2"`
	AddressType        *string   `json:"addressType,omitempty"`
	City               string    `json:"city"`
	Country            string    `json:"country"`
	DateOfBirth        time.Time `json:"dateOfBirth"`
	DepartmentId       *int64    `json:"departmentId,omitempty" validate:"numeric"`
	Dependents         *int32    `json:"dependents,omitempty"`
	EmergencyContactId *int64    `json:"emergencyContactId,omitempty" validate:"numeric"`
	GenderId           *int64    `json:"genderId,omitempty" validate:"string"`
	Id                 int64     `json:"id" validate:"numeric"`
	LatestContractId   *int64    `json:"latestContractId,omitempty" validate:"numeric"`
	MaritalStatusId    int64     `json:"maritalStatusId" validate:"numeric"`
	Nationality        string    `json:"nationality"`
	PostalCode         *string   `json:"postalCode"`
	State              *string   `json:"state"`
	UserId             int64     `json:"userId" validate:"numeric"`
}

// SingleUserResponse defines model for SingleUserResponse.
type SingleUserResponse struct {
	Data    *UserResponse `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
	Status  *int          `json:"status,omitempty"`
}

// UserRequest defines model for UserRequest.
type UserRequest struct {
	Avatar    *string             `json:"avatar,omitempty" validate:"string"`
	Email     openapi_types.Email `json:"email" validate:"email"`
	FirstName *string             `json:"firstName,omitempty" validate:"string"`
	LastName  *string             `json:"lastName,omitempty" validate:"string"`
	Password  string              `json:"password" validate:"string"`
	Username  string              `json:"username" validate:"string"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	AddressLine1            *string              `json:"addressLine1,omitempty"`
	AddressLine2            *string              `json:"addressLine2,omitempty"`
	Avatar                  *string              `json:"avatar,omitempty"`
	City                    *string              `json:"city,omitempty"`
	Country                 *string              `json:"country,omitempty"`
	CreatedAt               *time.Time           `json:"createdAt,omitempty"`
	DateOfBirth             *time.Time           `json:"dateOfBirth,omitempty"`
	DepartmentName          *string              `json:"departmentName,omitempty"`
	Dependents              *int32               `json:"dependents,omitempty"`
	Email                   *openapi_types.Email `json:"email,omitempty"`
	EmergencyContactAddress *string              `json:"emergencyContactAddress,omitempty"`
	EmergencyContactName    *string              `json:"emergencyContactName,omitempty"`
	EmergencyContactNumber  *int32               `json:"emergencyContactNumber,omitempty"`
	FirstName               *string              `json:"firstName,omitempty"`
	Gender                  *string              `json:"gender,omitempty"`
	Id                      *int64               `json:"id,omitempty"`
	LastName                *string              `json:"lastName,omitempty"`
	MaritalStatus           *string              `json:"maritalStatus,omitempty"`
	Nationality             *string              `json:"nationality,omitempty"`
	PostalCode              *string              `json:"postalCode,omitempty"`
	ProfileId               *int64               `json:"profileId,omitempty"`
	Role                    *string              `json:"role,omitempty"`
	State                   *string              `json:"state,omitempty"`
	Status                  *string              `json:"status,omitempty"`
	UpdatedAt               *time.Time           `json:"updatedAt,omitempty"`
	Username                *string              `json:"username,omitempty"`
}

// UserStatusesResponse defines model for UserStatusesResponse.
type UserStatusesResponse struct {
	Id         *int64  `json:"id,omitempty"`
	StatusName *string `json:"statusName,omitempty"`
}

// GetGendersParams defines parameters for GetGenders.
type GetGendersParams struct {
	// Offset Page number of the genders list
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Number of genders per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetMaritalStatusesParams defines parameters for GetMaritalStatuses.
type GetMaritalStatusesParams struct {
	// Offset Page number of the list
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Number of items per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	// Offset Page number of the users list
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Number of users per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetUsersStatusesParams defines parameters for GetUsersStatuses.
type GetUsersStatusesParams struct {
	// Offset Page number of the list
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Number of items per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostAuthJSONRequestBody defines body for PostAuth for application/json ContentType.
type PostAuthJSONRequestBody = LoginUserRequest

// PutProfilesJSONRequestBody defines body for PutProfiles for application/json ContentType.
type PutProfilesJSONRequestBody = PutProfileRequest

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = UserRequest

// PutUsersUserIdJSONRequestBody defines body for PutUsersUserId for application/json ContentType.
type PutUsersUserIdJSONRequestBody = UserRequest

// AsApiResponseData0 returns the union data inside the ApiResponse_Data as a ApiResponseData0
func (t ApiResponse_Data) AsApiResponseData0() (ApiResponseData0, error) {
	var body ApiResponseData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiResponseData0 overwrites any union data inside the ApiResponse_Data as the provided ApiResponseData0
func (t *ApiResponse_Data) FromApiResponseData0(v ApiResponseData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApiResponseData0 performs a merge with any union data inside the ApiResponse_Data, using the provided ApiResponseData0
func (t *ApiResponse_Data) MergeApiResponseData0(v ApiResponseData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsApiResponseData1 returns the union data inside the ApiResponse_Data as a ApiResponseData1
func (t ApiResponse_Data) AsApiResponseData1() (ApiResponseData1, error) {
	var body ApiResponseData1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiResponseData1 overwrites any union data inside the ApiResponse_Data as the provided ApiResponseData1
func (t *ApiResponse_Data) FromApiResponseData1(v ApiResponseData1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApiResponseData1 performs a merge with any union data inside the ApiResponse_Data, using the provided ApiResponseData1
func (t *ApiResponse_Data) MergeApiResponseData1(v ApiResponseData1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t ApiResponse_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiResponse_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get auth token
	// (POST /auth)
	PostAuth(c *gin.Context)
	// List Available Gender Options
	// (GET /genders)
	GetGenders(c *gin.Context, params GetGendersParams)
	// List Available Marital Status Options for Forms
	// (GET /marital-statuses)
	GetMaritalStatuses(c *gin.Context, params GetMaritalStatusesParams)
	// Update User profiles
	// (PUT /profiles)
	PutProfiles(c *gin.Context)
	// Get a list of users
	// (GET /users)
	GetUsers(c *gin.Context, params GetUsersParams)
	// Create a new user
	// (POST /users)
	PostUsers(c *gin.Context)
	// Get all user statuses
	// (GET /users/statuses)
	GetUsersStatuses(c *gin.Context, params GetUsersStatusesParams)
	// Delete a user
	// (DELETE /users/{userId})
	DeleteUsersUserId(c *gin.Context, userId int)
	// Get a user by ID
	// (GET /users/{userId})
	GetUsersUserId(c *gin.Context, userId int)
	// Update a user
	// (PUT /users/{userId})
	PutUsersUserId(c *gin.Context, userId int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAuth operation middleware
func (siw *ServerInterfaceWrapper) PostAuth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuth(c)
}

// GetGenders operation middleware
func (siw *ServerInterfaceWrapper) GetGenders(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGendersParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGenders(c, params)
}

// GetMaritalStatuses operation middleware
func (siw *ServerInterfaceWrapper) GetMaritalStatuses(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMaritalStatusesParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMaritalStatuses(c, params)
}

// PutProfiles operation middleware
func (siw *ServerInterfaceWrapper) PutProfiles(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutProfiles(c)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{"Administrator"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsers(c, params)
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsers(c)
}

// GetUsersStatuses operation middleware
func (siw *ServerInterfaceWrapper) GetUsersStatuses(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{"Administrator"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersStatusesParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersStatuses(c, params)
}

// DeleteUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUsersUserId(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int

	err = runtime.BindStyledParameter("simple", false, "userId", c.Param("userId"), &userId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteUsersUserId(c, userId)
}

// GetUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserId(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int

	err = runtime.BindStyledParameter("simple", false, "userId", c.Param("userId"), &userId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersUserId(c, userId)
}

// PutUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) PutUsersUserId(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int

	err = runtime.BindStyledParameter("simple", false, "userId", c.Param("userId"), &userId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutUsersUserId(c, userId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth", wrapper.PostAuth)
	router.GET(options.BaseURL+"/genders", wrapper.GetGenders)
	router.GET(options.BaseURL+"/marital-statuses", wrapper.GetMaritalStatuses)
	router.PUT(options.BaseURL+"/profiles", wrapper.PutProfiles)
	router.GET(options.BaseURL+"/users", wrapper.GetUsers)
	router.POST(options.BaseURL+"/users", wrapper.PostUsers)
	router.GET(options.BaseURL+"/users/statuses", wrapper.GetUsersStatuses)
	router.DELETE(options.BaseURL+"/users/:userId", wrapper.DeleteUsersUserId)
	router.GET(options.BaseURL+"/users/:userId", wrapper.GetUsersUserId)
	router.PUT(options.BaseURL+"/users/:userId", wrapper.PutUsersUserId)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xae2/bOBL/KgRv/zr4ISfZvcbAAue0uSJ7bRM0zR2wge/ASGObXYlUyVFSN/B3X5CU",
	"H6JoR24dJwsEWGxbheQ8OL+Z33ByT2OZ5VKAQE3791THE8iY/esgjkHrT/IPEB9B51JoMJ9zJXNQyMEu",
	"YnbR/9GsMv+GryzLU6B9+vkO3dcWxWluvmhUXIzpbNaiCr4UXEFC+9fVI4aL1fLmM8RIZy06yPl6BRKG",
	"zPwpijRlN0YyqgJaVAo4H9H+9X3tvHvKETK7uSaq/MCUYlM6G85aNAOt2RhWVs/NaFGNDAt70EiqjCHt",
	"Uy7w8GBpMhcIY1DW5rpdBU6k4t8YcilOlZJqvZmxTKDi36Oo13pYbEX/5d1cCVbKhiR4PzVdT1jyEb4U",
	"oHF7RaPvV/SGJUQ5uc30fAsigQ3qje3PP7DME/SepVCX0KI88a/3l6OG1/tOjrm40kYbZ0BNGcgYTz3U",
	"yIno6Izj5J/2p51YZjW9WvRrW7Kct42zxyDa8BUVayMb22NvWcoThmaDk2DUy5nWd1Iljyou4+LXV62M",
	"YTwB/ev/rln726D9e9Q+Hv79Jzrzge+UW1FtuNmLD6WAnxSMaJ/+rbtMad0yn3VDyWxd0OnCLg6FwxLx",
	"i+UHJr6bxMN7pjiy9NIeAXq9PQ1jbq5N02AO6lSkyB1m9MMOXuTNTZ72EFhLqnt2ujGwsee3MnTdqc/B",
	"YgOYHZsbPPK52LpLI5+LcRcFXig54imsLSAsSRRo/Y4L6FV16h0ckveMC3KJIb1WNh5UNw5yJCbb+Hxq",
	"3RGf7Pd7msCIFanJVwo0T0AgZya5L0+ufq+dF3OceqqIKco7EVwsC4HKW/+6/BhYb+rT+eiEK5x4fjo+",
	"jtpRrx31PkVR3/73O13hK2ZjG3kWJAcJ5ExhBgLPqnXVo2ah9N28qIoiA8VjGyQJ5Ca9lmR9GVONGBZk",
	"oMYg4ulrKZDFe1Paca7HlLZS4viejEoZgkbjSbVHV2arNWdfQoVtUFhaA+iJ4sj1JASNXGpk6Wu/GTB5",
	"6ejnJunFZE5v76X91GBvoR833JbO8RgtN91UKb2adKperF9kq5rLy3S4THQhanzJxTiFH+fGftHbZ5Hb",
	"2B+xW4ZMeXocdljGvklhWpVuNnVrOp/z8Q/0LSv5o3lPtoineR/z403aiCuNdT5vFNiNdSkLnW9t242A",
	"vbSZK/IM2ETQYVZcbxdSPJAvRLaadbCbAbqBwpE38k5wMSaXqAC25HGnvcPghh+DVJCnvZMikc1p2tW/",
	"g0sVMIRkgJXedzP9qpK6bTlbHQeD2CrswiS0M8S9Dhtyr2Ba2TqrBGjcwMVAnf8/HD7+UXWX/MYEkLf8",
	"Jm14QJHdQDW8egeHvaOffzl+9Y9GjtomBS645U7f8rbLkj4p8yiLLdGhTR6pakygTnuH5PjiJMi5XLd4",
	"1tRMJVPvcJPaaDMyth70ATpAWYz8NuiHIk+2xf3WOX8t89jDW9xgjeV1lcwhEBeK4/TSMDOnwA0wBWpQ",
	"uBzn/vWvuTq//fcTbbmZjX0ttz9dypog5q5+cTGSrkvXseK5CT3b63PiSCAZSUVOP16QGxb/ASLpmEM4",
	"WgvOcxDkUhYqBrtkcHFGW/QWlHanRJ2o0zMukDkIlnPap4edqBPZuogTa0WXlQaYsDZ/Gh9bBJhopRdS",
	"ozXRVVrQeCKTqRsnCARht7A8T3lsN3U/aymW46qHCG7tJd6r6aaNsB9cFFiND6LeY8ifs2zXzK9ehn2b",
	"Jq9dGTTuPIqinWmwbnwT0ONMWA5E5pym43TZnTc2jL2aqWOAUmQZM8SCvgUkJrjIYthomdy1na6BwFJH",
	"OjTbuq5clJOgQCC+BSxfw230KpYB2vXXPnYu2BiIsOWOyBHBCZDycJJyO63iZtmXAuyLlMtXVI5G2lbS",
	"pasWD2fBjskX+2EhcS4tB0Vy066FJaY842sE9kIShzUc7C4Kg9OGwJ0PrAtXjHxCOJywhJRrnwkSbKB3",
	"TREkQrrgL+Mc5ugoy4gN29UCcj0097sEzzvj5sEt4/Y9hbirIedWol7B0hwTDkQl32nrsnpuQpM3JPkO",
	"VO0HTXY68JfD0toR1CZMlZuI27W47ReI7QNiYedb+mVY3Sroqkthjr6S5duAyosQmVrMjfQj8an6ZGrP",
	"hGr1N4IC11gqR65cb/GEof0f95zEpSB2rX7iAP8gkQwWv/qzZSg7dxJDZEm+jLB5vC6CzsWpQc/G0mDn",
	"tt9REOzBeyoLTtZfrSxUJ+Ibi4G7pZfcv5vcTwdJxgXXqBhKRT382FbF8/wSPhZW75lgY8iM6cPyESjc",
	"Lc/B8xjp/Qk75cBIK5TF4M66j8RP3i37Cd7rTl07TxgRpcobL3yRNrtNqLUNgRdi/WgZtAmrviynoi8M",
	"4/sYRoOEmaYO63oZ6RUEefTY4efeDeFnLpRScK/XVQi9sd8tiq7mI3sPQzZWc1bO77P5E7ldWk2Kq7Hb",
	"IFyP9kWFrYucBxIvNzn7CXs4L7U256C9ey/ac70ZEG3XOU8F3h9dhN5Mydmbhyr6mo5tb458BnQh2mvw",
	"F/MmcBboZRoEv0tg6jZcVxO4JYVKaYua/7uRS7/bTWXM0onU2H8VvYq6LOfd2x41N1AKup9f5IkbuNB6",
	"DT2fx4gmClJjA0HpIo1V37YXUeG9edfPPBVJLrlA9+KQGTu5GJeHuum3Xh7nO2M2nP0ZAAD//7cfGOAw",
	"NAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
