version: "3"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=erp_go
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d erp_go"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  app:
    container_name: erp-go-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/backend/vendor
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/erp_go?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
