FROM node:latest as node-base

WORKDIR /app/frontend
COPY frontend/open-source-erp/package.json frontend/open-source-erp/yarn.lock ./
RUN yarn install
COPY frontend/open-source-erp/ ./

FROM golang:1.21.4-alpine3.18

RUN go install github.com/cosmtrek/air@latest

RUN apk add --update nodejs npm yarn

WORKDIR /app

COPY backend/go.mod backend/go.sum ./backend/
WORKDIR /app/backend
RUN go mod download
RUN go mod vendor

WORKDIR /app

COPY backend/ ./backend/

COPY --from=node-base /app/frontend ./frontend/open-source-erp

COPY . .

RUN apk add --no-cache make && make --version

CMD ["make", "dev"]
