FROM golang:1.21.4-alpine3.18

RUN apk add --update --no-cache nodejs-current yarn
RUN yarn global add typescript

RUN go install github.com/cosmtrek/air@latest

RUN apk add --no-cache make

WORKDIR /app/backend

COPY backend/go.mod backend/go.sum ./
RUN go mod download
RUN go mod vendor

COPY backend/ ./

WORKDIR /app/frontend/open-source-erp

COPY frontend/open-source-erp/package.json ./

RUN yarn install

COPY frontend/open-source-erp/ ./

WORKDIR /app

COPY makefile .

CMD ["make", "dev"]
